# Netlify configuration file

[build]
  publish = "./"
  command = "# no build command"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  framework = "#custom"
  command = "node server.js"
  port = 5000
  targetPort = 5000
  publish = "./"